In [35]:
import numpy as np

# Create an array of student marks. Find the average, max, mean, percentage, Failures and Toppers.

In [43]:
totalMarks = 1100
marks = np.random.randint(1, 1101, 100)
marks

array([ 295,  321,  882,  621,  126,  537,  641,   83,  949,  972,  990,
        394,  438,   17,  603,  912,  274,  241,  660,  389,  194,  640,
        361,  180,  487,  527,  299,  828,  584,  196,  285,  383,  308,
        608,  844, 1032,  735,  422,  100,  637,  423,  381,   90,  547,
        617,  305,  636, 1075,  871,   76,   42,  371,  829,  295,  682,
        347,  477,  675,  796,  518,  177,  998,  662, 1030,  313, 1065,
        850, 1086,  926,  718,  867,  287,   60,  421,   87,  149,  386,
        109, 1051,  749,    8,  575,  882,  798,  710,  750,  376, 1024,
        793,  304,   33,  555,  555,  594,  123, 1092,  911, 1056,  190,
        255], dtype=int32)

Average

In [44]:
avg = np.average(marks)
avg

np.float64(536.23)

Max

In [50]:
maximun = np.max(marks)
maximun

np.int32(1092)

Min

In [53]:
minimum = np.min(marks)
minimum

np.int32(8)

Mean

In [46]:
mean = np.mean(marks)
mean

np.float64(536.23)

Percentage

In [47]:
percentage = marks * 100/ totalMarks
percentage = np.round(percentage, 2)
percentage

array([26.82, 29.18, 80.18, 56.45, 11.45, 48.82, 58.27,  7.55, 86.27,
       88.36, 90.  , 35.82, 39.82,  1.55, 54.82, 82.91, 24.91, 21.91,
       60.  , 35.36, 17.64, 58.18, 32.82, 16.36, 44.27, 47.91, 27.18,
       75.27, 53.09, 17.82, 25.91, 34.82, 28.  , 55.27, 76.73, 93.82,
       66.82, 38.36,  9.09, 57.91, 38.45, 34.64,  8.18, 49.73, 56.09,
       27.73, 57.82, 97.73, 79.18,  6.91,  3.82, 33.73, 75.36, 26.82,
       62.  , 31.55, 43.36, 61.36, 72.36, 47.09, 16.09, 90.73, 60.18,
       93.64, 28.45, 96.82, 77.27, 98.73, 84.18, 65.27, 78.82, 26.09,
        5.45, 38.27,  7.91, 13.55, 35.09,  9.91, 95.55, 68.09,  0.73,
       52.27, 80.18, 72.55, 64.55, 68.18, 34.18, 93.09, 72.09, 27.64,
        3.  , 50.45, 50.45, 54.  , 11.18, 99.27, 82.82, 96.  , 17.27,
       23.18])

Failures

In [48]:
failures = percentage <= 40 
failures = marks[failures]
failures

array([295, 321, 126,  83, 394, 438,  17, 274, 241, 389, 194, 361, 180,
       299, 196, 285, 383, 308, 422, 100, 423, 381,  90, 305,  76,  42,
       371, 295, 347, 177, 313, 287,  60, 421,  87, 149, 386, 109,   8,
       376, 304,  33, 123, 190, 255], dtype=int32)

Toppers

In [62]:
toppers = percentage >= 80
toppers = marks[toppers]
toppers

array([ 882,  949,  972,  990,  912, 1032, 1075,  998, 1030, 1065, 1086,
        926, 1051,  882, 1024, 1092,  911, 1056], dtype=int32)

In [66]:
dic = { 
    "Total Marks": totalMarks,
    "Average" : avg,
    "Maximum" : max,
    "Minimum" : min,
    "Mean" : mean,
    "Percentage" : percentage,
    "Failure" : failures,
    "Topper" : toppers 
}

In [68]:
for keys,values in dic.items():
    print(f"{keys} = {values}")

Total Marks = 1100
Average = 536.23
Maximum = <built-in function max>
Minimum = <built-in function min>
Mean = 536.23
Percentage = [26.82 29.18 80.18 56.45 11.45 48.82 58.27  7.55 86.27 88.36 90.   35.82
 39.82  1.55 54.82 82.91 24.91 21.91 60.   35.36 17.64 58.18 32.82 16.36
 44.27 47.91 27.18 75.27 53.09 17.82 25.91 34.82 28.   55.27 76.73 93.82
 66.82 38.36  9.09 57.91 38.45 34.64  8.18 49.73 56.09 27.73 57.82 97.73
 79.18  6.91  3.82 33.73 75.36 26.82 62.   31.55 43.36 61.36 72.36 47.09
 16.09 90.73 60.18 93.64 28.45 96.82 77.27 98.73 84.18 65.27 78.82 26.09
  5.45 38.27  7.91 13.55 35.09  9.91 95.55 68.09  0.73 52.27 80.18 72.55
 64.55 68.18 34.18 93.09 72.09 27.64  3.   50.45 50.45 54.   11.18 99.27
 82.82 96.   17.27 23.18]
Failure = [295 321 126  83 394 438  17 274 241 389 194 361 180 299 196 285 383 308
 422 100 423 381  90 305  76  42 371 295 347 177 313 287  60 421  87 149
 386 109   8 376 304  33 123 190 255]
Topper = [ 882  949  972  990  912 1032 1075  998 1030 1065 1086 