In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,50,10)
arr

array([20, 35, 41,  8, 22, 22,  3, 13,  3, 47], dtype=int32)

In [3]:
arr[6]

np.int32(3)

In [4]:
arr[1:5]


array([35, 41,  8, 22], dtype=int32)

In [5]:
arr[0:9:2]

array([20, 41, 22,  3,  3], dtype=int32)

In [6]:
arr = np.random.randint(0,50,9).reshape(3,3)
arr

array([[23, 31, 40],
       [40, 21, 15],
       [ 2, 22, 44]], dtype=int32)

In [7]:
arr[1]

array([40, 21, 15], dtype=int32)

In [8]:
arr[2,1]

np.int32(22)

In [9]:
arr = np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [10]:
arr[3:,4:]

array([[23, 24],
       [29, 30],
       [35, 36]])

In [11]:
arr[:,3]

array([ 4, 10, 16, 22, 28, 34])

In [12]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
bolean_indexing = arr % 2 != 0 
bolean_indexing
arr[bolean_indexing]

array([11, 13, 15, 17, 19])