In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5,6,7,8,9]

In [4]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
twoDimatinalList = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(twoDimatinalList)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [8]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [10]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [14]:
arr = np.random.rand(10)
arr

array([0.86826226, 0.90908045, 0.86736777, 0.45319333, 0.80541976,
       0.05548462, 0.4826921 , 0.70243568, 0.59061728, 0.32120282])

In [17]:
arr = np.random.randn(10)
arr

array([-0.65404675, -0.16779094,  1.75955298,  0.42735747,  0.8109697 ,
       -2.08000831,  0.23676954, -0.48860196, -1.42921583, -0.66633097])

In [22]:
arr = np.random.randint(1,10,4)
arr

array([1, 2, 1, 2], dtype=int32)

In [23]:
arr.shape

(4,)

In [24]:
arr.size

4

In [25]:
arr.dtype

dtype('int32')

In [26]:
arr.min()

np.int32(1)

In [27]:
arr.max()

np.int32(2)

In [28]:
arr.sum()

np.int64(6)

In [33]:
arr = arr.reshape(2,2)
arr

array([[1, 2],
       [1, 2]], dtype=int32)

In [35]:
np.sum(arr,axis=1)

array([3, 3])

In [36]:
arr.mean()

np.float64(1.5)

In [37]:
arr.std()

np.float64(0.5)

In [38]:
arr.argmax()

np.int64(1)

In [39]:
arr.argmin()

np.int64(0)