In [1]:
import numpy as np

## Array Opreation

Arthematic Opreation

In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [3]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [4]:
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [5]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [6]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
arr1 // arr2

array([0, 0, 0, 0, 0])

In [8]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [9]:
arr1 % arr2

array([1, 2, 3, 4, 5])

In [10]:
arr = np.arange(1,10).reshape(3,3)
ARR = np.arange(11,20).reshape(3,3)

In [11]:
arr + ARR

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

Broadcasting

In [12]:
l = [10,20,30,40,50]
arr = np.array(l)

In [13]:
arr + 10

array([20, 30, 40, 50, 60])

In [14]:
arr - 10

array([ 0, 10, 20, 30, 40])

In [15]:
arr * 10

array([100, 200, 300, 400, 500])

In [16]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr + 30

array([[31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

Deep and Shalow Copy

In [18]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
slice = arr[:6]
slice = slice * 10
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
a = arr
a[0] = 99
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Opreation

In [27]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.arange(5,9).reshape(2,2)

In [28]:
mat1

array([[1, 2],
       [3, 4]])

In [29]:
mat2

array([[5, 6],
       [7, 8]])

In [36]:
# Multipilication in Matrix
mat1 @ mat2
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [37]:
# Transpose in Matrix
mat1.T

array([[1, 3],
       [2, 4]])

Advanced Array Manipulation

In [41]:
# Stacking Array

In [44]:
A = np.arange(1,6)
B = np.arange(6,11)

In [45]:
A

array([1, 2, 3, 4, 5])

In [46]:
B

array([ 6,  7,  8,  9, 10])

In [47]:
# Vertical Stack
np.vstack((A,B))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
# Horizontal Stack
np.hstack((A,B))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# Colume Stack
np.column_stack((A,B))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [50]:
# Splitting Array

In [56]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
# Horizontal Split
np.hsplit(arr,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [66]:
# Vertical Split
np.vsplit(arr,2)