In [4]:
import numpy as np

## Valid Sudoku

In [6]:
sudoku = np.array([
      [5, 3, 4, 6, 7, 8, 9, 1, 2],
      [6, 7, 2, 1, 9, 5, 3, 4, 8],
      [1, 9, 8, 3, 4, 2, 5, 6, 7],

      [8, 5, 9, 7, 6, 1, 4, 2, 3],
      [4, 2, 6, 8, 5, 3, 7, 9, 1],
      [7, 1, 3, 9, 2, 4, 8, 5, 6],

      [9, 6, 1, 5, 3, 7, 2, 8, 4],
      [2, 8, 7, 4, 1, 9, 6, 3, 5],
      [3, 4, 5, 2, 8, 6, 1, 7, 9]
    ])


In [9]:
#For Rows
rows = np.sum(sudoku, axis = 1)
for i in rows:
    if i != 45:
        print("Sudoku is'nt valid")
        break
else:
    print("Sudoku is valid for rows")

Sudoku is valid for rows


In [11]:
#For Columns
columns = np.sum(sudoku, axis = 0)
for i in columns:
    if i != 45:
        print("Sudoku is'nt valid")
        break
else:
    print("Sudoku is valid for columns")

Sudoku is valid for columns


In [26]:
# For Blocks
for i in range(0,9,3):
    for j in range(0,9,3):
        n = sudoku[ i : i + 3 , j : j + 3 ]
        print(np.sum(n))

45
45
45
45
45
45
45
45
45


## Generals Question

In [77]:
# Columns: [Age, Math's marks, Science marks]
data = np.array([
    [16,67,98],   # Student  01
    [15,86,56],   # Student  02
    [16,78,25],   # Student  03
    [17,65,70],   # Student  04
    [14,90,93]    # Student  05
])

In [78]:
# Gete the shape of the matrix
shape = data.shape
shape

(5, 3)

In [79]:
# Find the avg age of student
age = data[0:,0]
np.average(age)

np.float64(15.6)

In [80]:
# Extract Math marks of all student
math_mark = data[:,1]
math_mark

array([67, 86, 78, 65, 90])

In [81]:
# Find the Highest Science marks
sci_marks = data[:,2]
np.max(sci_marks)

np.int64(98)

In [82]:
# Get detail of the student who scored more than 90
marks = (math_mark + sci_marks) * 100/200
marks[marks >= 90]

array([91.5])

In [83]:
# Increse math marks of all student by 5
new_maths_marks = math_mark + 5 * 100/200
new_maths_marks

array([69.5, 88.5, 80.5, 67.5, 92.5])

In [84]:
# Find How many Student are Younger than 16
is_young = age[age > 16]
len(is_young)

1

In [85]:
# Calculate the avg marks in each subject(Column-Wise Mean)
np.mean(data[:,1:],axis = 1)

array([82.5, 71. , 51.5, 67.5, 91.5])

In [86]:
# Get dat of student who scored at least 80 in both subject
marks[marks >= 80]

array([82.5, 91.5])

In [89]:
# Replace all science marks > 25 with 0
sci_marks < 25

array([False, False, False, False, False])